import enum
from sqlalchemy import (
    Column, Integer, ForeignKey, CheckConstraint, Index, Enum, text,
)
from sqlalchemy.dialects.postgresql import UUID

from app.db.base import Base


# NOTE: this enum's labels in Postgres are 'LECTURE'/'LAB' (uppercase, the
# Python member names) — unlike RunKind/RunStatus which use lowercase values.
# Alembic autogenerated the type that way for college_slot_kind. Do NOT add
# `values_callable` to the Column below; it would change the labels SQLAlchemy
# sends and break inserts. If you ever rebuild the DB from scratch and want
# consistency, drop the type, redefine with values_callable, and recreate.
class CollegeSlotKind(str, enum.Enum):
    LECTURE = "lecture"
    LAB = "lab"


class CollegeAssignment(Base):
    __tablename__ = "college_assignments"
    __table_args__ = (
        CheckConstraint("day_of_week BETWEEN 0 AND 6"),
        CheckConstraint("period BETWEEN 1 AND 15"),
        Index("uq_college_room_slot",    "run_id", "day_of_week", "period", "room_id",    unique=True),
        Index("uq_college_faculty_slot", "run_id", "day_of_week", "period", "faculty_id", unique=True),
        Index("uq_college_section_slot", "run_id", "day_of_week", "period", "section_id", unique=True),
        Index("idx_college_assignments_run_day", "run_id", "day_of_week"),
    )

    id           = Column(UUID(as_uuid=True), primary_key=True,
                          server_default=text("uuid_generate_v4()"))
    run_id       = Column(UUID(as_uuid=True),
                          ForeignKey("runs.id", ondelete="CASCADE"),
                          nullable=False, index=True)
    day_of_week  = Column(Integer, nullable=False)
    period       = Column(Integer, nullable=False)
    course_id    = Column(UUID(as_uuid=True),
                          ForeignKey("college_courses.id", ondelete="CASCADE"),
                          nullable=False)
    faculty_id   = Column(UUID(as_uuid=True),
                          ForeignKey("college_faculty.id", ondelete="CASCADE"),
                          nullable=False)
    section_id   = Column(UUID(as_uuid=True),
                          ForeignKey("college_sections.id", ondelete="CASCADE"),
                          nullable=False)
    room_id      = Column(UUID(as_uuid=True),
                          ForeignKey("college_rooms.id", ondelete="CASCADE"),
                          nullable=False)
    slot_kind    = Column(Enum(CollegeSlotKind, name="college_slot_kind"), nullable=False)
