"""v2_003_college_branch

Revision ID: v2_003
Revises: v2_002
Create Date: 2026-05-06 00:52:31.330823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'v2_003'
down_revision: Union[str, None] = 'v2_002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college_departments',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'code')
    )
    op.create_index(op.f('ix_college_departments_run_id'), 'college_departments', ['run_id'], unique=False)
    op.create_table('college_hard_constraints',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('max_consecutive_periods', sa.Integer(), nullable=False),
    sa.Column('max_periods_per_day_per_faculty', sa.Integer(), nullable=False),
    sa.Column('lunch_period_index', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_consecutive_periods BETWEEN 1 AND 10'),
    sa.CheckConstraint('max_periods_per_day_per_faculty BETWEEN 1 AND 15'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('college_rooms',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=False),
    sa.CheckConstraint('capacity BETWEEN 1 AND 1000'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'name')
    )
    op.create_index(op.f('ix_college_rooms_room_type'), 'college_rooms', ['room_type'], unique=False)
    op.create_index(op.f('ix_college_rooms_run_id'), 'college_rooms', ['run_id'], unique=False)
    op.create_table('college_time_config',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('working_days', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('periods_per_day', sa.Integer(), nullable=False),
    sa.Column('period_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.CheckConstraint('period_duration_minutes BETWEEN 15 AND 180'),
    sa.CheckConstraint('periods_per_day BETWEEN 1 AND 15'),
    sa.CheckConstraint('semester BETWEEN 1 AND 8'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('college_courses',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('lectures_per_week', sa.Integer(), nullable=False),
    sa.Column('has_lab', sa.Boolean(), nullable=False),
    sa.Column('required_lecture_room_type', sa.String(length=50), nullable=False),
    sa.Column('required_lab_room_type', sa.String(length=50), nullable=True),
    sa.Column('enrolled_students', sa.Integer(), nullable=False),
    sa.Column('is_elective', sa.Boolean(), nullable=False),
    sa.CheckConstraint('credits BETWEEN 1 AND 6'),
    sa.CheckConstraint('enrolled_students BETWEEN 1 AND 1000'),
    sa.CheckConstraint('lectures_per_week BETWEEN 1 AND 10'),
    sa.CheckConstraint('year BETWEEN 1 AND 5'),
    sa.ForeignKeyConstraint(['department_id'], ['college_departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'code')
    )
    op.create_index(op.f('ix_college_courses_department_id'), 'college_courses', ['department_id'], unique=False)
    op.create_index(op.f('ix_college_courses_run_id'), 'college_courses', ['run_id'], unique=False)
    op.create_table('college_faculty',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('max_hours_per_week', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_hours_per_week BETWEEN 1 AND 40'),
    sa.ForeignKeyConstraint(['department_id'], ['college_departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'code')
    )
    op.create_index(op.f('ix_college_faculty_run_id'), 'college_faculty', ['run_id'], unique=False)
    op.create_table('college_faculty_courses',
    sa.Column('faculty_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['college_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['college_faculty.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('faculty_id', 'course_id')
    )
    op.create_index(op.f('ix_college_faculty_courses_course_id'), 'college_faculty_courses', ['course_id'], unique=False)
    op.create_table('college_sections',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['college_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'course_id', 'name')
    )
    op.create_index(op.f('ix_college_sections_run_id'), 'college_sections', ['run_id'], unique=False)
    op.create_table('college_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('faculty_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('slot_kind', sa.Enum('LECTURE', 'LAB', name='college_slot_kind'), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6'),
    sa.CheckConstraint('period BETWEEN 1 AND 15'),
    sa.ForeignKeyConstraint(['course_id'], ['college_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['college_faculty.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['college_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['college_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_college_assignments_run_day', 'college_assignments', ['run_id', 'day_of_week'], unique=False)
    op.create_index(op.f('ix_college_assignments_run_id'), 'college_assignments', ['run_id'], unique=False)
    op.create_index('uq_college_faculty_slot', 'college_assignments', ['run_id', 'day_of_week', 'period', 'faculty_id'], unique=True)
    op.create_index('uq_college_room_slot', 'college_assignments', ['run_id', 'day_of_week', 'period', 'room_id'], unique=True)
    op.create_index('uq_college_section_slot', 'college_assignments', ['run_id', 'day_of_week', 'period', 'section_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_college_section_slot', table_name='college_assignments')
    op.drop_index('uq_college_room_slot', table_name='college_assignments')
    op.drop_index('uq_college_faculty_slot', table_name='college_assignments')
    op.drop_index(op.f('ix_college_assignments_run_id'), table_name='college_assignments')
    op.drop_index('idx_college_assignments_run_day', table_name='college_assignments')
    op.drop_table('college_assignments')
    op.drop_index(op.f('ix_college_sections_run_id'), table_name='college_sections')
    op.drop_table('college_sections')
    op.drop_index(op.f('ix_college_faculty_courses_course_id'), table_name='college_faculty_courses')
    op.drop_table('college_faculty_courses')
    op.drop_index(op.f('ix_college_faculty_run_id'), table_name='college_faculty')
    op.drop_table('college_faculty')
    op.drop_index(op.f('ix_college_courses_run_id'), table_name='college_courses')
    op.drop_index(op.f('ix_college_courses_department_id'), table_name='college_courses')
    op.drop_table('college_courses')
    op.drop_table('college_time_config')
    op.drop_index(op.f('ix_college_rooms_run_id'), table_name='college_rooms')
    op.drop_index(op.f('ix_college_rooms_room_type'), table_name='college_rooms')
    op.drop_table('college_rooms')
    op.drop_table('college_hard_constraints')
    op.drop_index(op.f('ix_college_departments_run_id'), table_name='college_departments')
    op.drop_table('college_departments')
    # ### end Alembic commands ###
