"""v2_002_school_branch

Revision ID: v2_002
Revises: v2_001
Create Date: 2026-05-06 00:45:59.319609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'v2_002'
down_revision: Union[str, None] = 'v2_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_classes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.CheckConstraint('size BETWEEN 1 AND 500'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'name')
    )
    op.create_index(op.f('ix_school_classes_run_id'), 'school_classes', ['run_id'], unique=False)
    op.create_table('school_hard_constraints',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('max_consecutive_periods', sa.Integer(), nullable=False),
    sa.Column('max_periods_per_day_per_teacher', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_consecutive_periods BETWEEN 1 AND 10'),
    sa.CheckConstraint('max_periods_per_day_per_teacher BETWEEN 1 AND 15'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('school_rooms',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.CheckConstraint('capacity BETWEEN 1 AND 1000'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'name')
    )
    op.create_index(op.f('ix_school_rooms_run_id'), 'school_rooms', ['run_id'], unique=False)
    op.create_table('school_subjects',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('periods_per_week', sa.Integer(), nullable=False),
    sa.CheckConstraint('periods_per_week BETWEEN 1 AND 15'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'code')
    )
    op.create_index(op.f('ix_school_subjects_run_id'), 'school_subjects', ['run_id'], unique=False)
    op.create_table('school_teachers',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'name')
    )
    op.create_index(op.f('ix_school_teachers_run_id'), 'school_teachers', ['run_id'], unique=False)
    op.create_table('school_time_config',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('working_days', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('periods_per_day', sa.Integer(), nullable=False),
    sa.Column('period_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('lunch_after_period', sa.Integer(), nullable=False),
    sa.Column('lunch_duration_minutes', sa.Integer(), nullable=False),
    sa.CheckConstraint('period_duration_minutes BETWEEN 15 AND 180'),
    sa.CheckConstraint('periods_per_day BETWEEN 1 AND 15'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('school_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6'),
    sa.CheckConstraint('period BETWEEN 1 AND 15'),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['school_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['school_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['school_teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_school_assignments_run_day', 'school_assignments', ['run_id', 'day_of_week'], unique=False)
    op.create_index(op.f('ix_school_assignments_run_id'), 'school_assignments', ['run_id'], unique=False)
    op.create_index('uq_school_class_slot', 'school_assignments', ['run_id', 'day_of_week', 'period', 'class_id'], unique=True)
    op.create_index('uq_school_room_slot', 'school_assignments', ['run_id', 'day_of_week', 'period', 'room_id'], unique=True)
    op.create_index('uq_school_teacher_slot', 'school_assignments', ['run_id', 'day_of_week', 'period', 'teacher_id'], unique=True)
    op.create_table('school_subject_classes',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['school_subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id', 'class_id')
    )
    op.create_index(op.f('ix_school_subject_classes_class_id'), 'school_subject_classes', ['class_id'], unique=False)
    op.create_table('school_teacher_subjects',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['school_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['school_teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'subject_id')
    )
    op.create_index(op.f('ix_school_teacher_subjects_subject_id'), 'school_teacher_subjects', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_teacher_subjects_subject_id'), table_name='school_teacher_subjects')
    op.drop_table('school_teacher_subjects')
    op.drop_index(op.f('ix_school_subject_classes_class_id'), table_name='school_subject_classes')
    op.drop_table('school_subject_classes')
    op.drop_index('uq_school_teacher_slot', table_name='school_assignments')
    op.drop_index('uq_school_room_slot', table_name='school_assignments')
    op.drop_index('uq_school_class_slot', table_name='school_assignments')
    op.drop_index(op.f('ix_school_assignments_run_id'), table_name='school_assignments')
    op.drop_index('idx_school_assignments_run_day', table_name='school_assignments')
    op.drop_table('school_assignments')
    op.drop_table('school_time_config')
    op.drop_index(op.f('ix_school_teachers_run_id'), table_name='school_teachers')
    op.drop_table('school_teachers')
    op.drop_index(op.f('ix_school_subjects_run_id'), table_name='school_subjects')
    op.drop_table('school_subjects')
    op.drop_index(op.f('ix_school_rooms_run_id'), table_name='school_rooms')
    op.drop_table('school_rooms')
    op.drop_table('school_hard_constraints')
    op.drop_index(op.f('ix_school_classes_run_id'), table_name='school_classes')
    op.drop_table('school_classes')
    # ### end Alembic commands ###
